import * as React from "react";
import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";
import { format } from "date-fns";
import { formatDuration } from "@/lib/utils";
import type { ExportWorkout } from "./types";

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: "Helvetica" },
  h1: { fontSize: 18, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  h2: { fontSize: 12, fontFamily: "Helvetica-Bold", marginTop: 12, marginBottom: 4 },
  meta: { fontSize: 9, color: "#555", marginBottom: 12 },
  workout: {
    borderBottom: "1pt solid #ddd",
    paddingVertical: 6,
    flexDirection: "row",
  },
  dateCol: { width: 80, color: "#555" },
  titleCol: { flex: 1 },
  sport: { fontSize: 9, color: "#333", marginTop: 2 },
  steps: { marginTop: 3, color: "#444" },
});

export function WeeklyPlanPdf({
  planName,
  workouts,
}: {
  planName: string;
  workouts: ExportWorkout[];
}) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.h1}>{planName}</Text>
        <Text style={styles.meta}>
          {workouts.length} workouts · generated by Ultracoach
        </Text>

        {workouts.map((w) => (
          <View key={w.id} style={styles.workout} wrap={false}>
            <View style={styles.dateCol}>
              <Text>{format(w.date, "EEE MMM d")}</Text>
              <Text style={{ color: "#888" }}>
                {formatDuration(w.durationSeconds)}
              </Text>
            </View>
            <View style={styles.titleCol}>
              <Text style={{ fontFamily: "Helvetica-Bold" }}>{w.title}</Text>
              <Text style={styles.sport}>
                {w.sport} · {w.type}
                {w.estimatedTss ? ` · ${w.estimatedTss} TSS` : ""}
              </Text>
              {w.description ? <Text style={styles.steps}>{w.description}</Text> : null}
              {w.steps?.length ? (
                <Text style={styles.steps}>
                  {w.steps
                    .map((s) => {
                      const d = s.durationSeconds
                        ? formatDuration(s.durationSeconds)
                        : s.distanceMeters
                          ? `${(s.distanceMeters / 1000).toFixed(2)} km`
                          : "";
                      const t = s.target?.type
                        ? `@ ${s.target.type}${
                            s.target.low !== undefined ? ` ${s.target.low}-${s.target.high}` : ""
                          }`
                        : "";
                      return `• ${s.kind.toUpperCase()} ${s.label} ${d} ${t}`.trim();
                    })
                    .join("   ")}
                </Text>
              ) : null}
            </View>
          </View>
        ))}
      </Page>
    </Document>
  );
}

export async function renderPlanPdf(planName: string, workouts: ExportWorkout[]): Promise<Buffer> {
  const instance = pdf(<WeeklyPlanPdf planName={planName} workouts={workouts} />);
  const stream = await instance.toBuffer();
  return await streamToBuffer(stream);
}

async function streamToBuffer(stream: NodeJS.ReadableStream): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    stream.on("data", (c) => chunks.push(Buffer.isBuffer(c) ? c : Buffer.from(c)));
    stream.on("end", () => resolve(Buffer.concat(chunks)));
    stream.on("error", reject);
  });
}
